CREATE TABLE tbl_types(
 index_no       INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY
,pokemon_type   VARCHAR2(20)
);

CREATE TABLE tbl_weakness (
 index_no             INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY
,attacker_move_type   VARCHAR2(20)
,defender_type        VARCHAR2(20)
,effect               INTEGER CHECK (effect IN (0, 1, 2))
,CONSTRAINT fk_tbl_weakness_tbl_types_1 FOREIGN KEY (attacker_move_type) REFERENCES tbl_types (index_no)
,CONSTRAINT fk_tbl_weakness_tbl_types_2 FOREIGN KEY (defender_type) REFERENCES tbl_types (index_no)
);

CREATE TABLE tbl_pokemon (
 id                  INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY
,name                VARCHAR2(50)
,evolve_to           INTEGER
,evolution_method    VARCHAR(10) CHECK (evolution_method IN ('level', 'item', 'trade'))
,type_1              INTEGER
,type_2              INTEGER
,hp                  INTEGER
,attack              INTEGER
,defense             INTEGER
,sp_atk              INTEGER
,sp_def              INTEGER
,speed               INTEGER
,is_legendary        INTEGER CHECK (is_legendary IN (0, 1))
,mega_flag           INTEGER CHECK (mega_flag IN (0, 1))
,CONSTRAINT fk_tbl_pokemon_tbl_types_1 FOREIGN KEY (type_1) REFERENCES tbl_types (index_no)
,CONSTRAINT fk_tbl_pokemon_tbl_types_2 FOREIGN KEY (type_2) REFERENCES tbl_types (index_no)
);

CREATE TABLE tbl_moves (
 id                INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY
,name              VARCHAR2(30)
,damage_category   VARCHAR2(10) CHECK (damage_category IN ('physical', 'special', 'status'))
,type              INTEGER
,status            INTEGER
,status_rate       NUMBER(0,2)
,description       VARCHAR(255)
,CONSTRAINT fk_tbl_moves_tbl_types FOREIGN KEY (type) REFERENCES tbl_types (index_no)
,CONSTRAINT fk_tbl_moves_tbl_status FOREIGN KEY (type) REFERENCES tbl_status (index_no)
);

CREATE TABLE tbl_mega_pokemon (
 pokemon_id     INTEGER
,pokemon_name   VARCHAR2(50)
,type_1         INTEGER
,type_2         INTEGER
,hp             INTEGER
,attack         INTEGER
,defense        INTEGER
,sp_atk         INTEGER
,sp_def         INTEGER
,speed          INTEGER
,is_legendary   INTEGER
);


